// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdn4Czb2DnqQOFvTQrVeYBCl4L_mRJBkQ',
    appId: '1:1074086011061:web:b6874e4584ae9cfaae1efc',
    messagingSenderId: '1074086011061',
    projectId: 'travel-cost-log',
    authDomain: 'travel-cost-log.firebaseapp.com',
    storageBucket: 'travel-cost-log.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbCSlbtnLnCAmvEevC09w9yh3Fb7HVvIA',
    appId: '1:1074086011061:android:08baf50909285b42ae1efc',
    messagingSenderId: '1074086011061',
    projectId: 'travel-cost-log',
    storageBucket: 'travel-cost-log.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxR3DBjvevM9E-QAJm_Pqn2jU2hUQbNmg',
    appId: '1:1074086011061:ios:689848a81f466d44ae1efc',
    messagingSenderId: '1074086011061',
    projectId: 'travel-cost-log',
    storageBucket: 'travel-cost-log.appspot.com',
    iosClientId: '1074086011061-00r8q1aehj5fbqh5j3dr53scfq40kf1b.apps.googleusercontent.com',
    iosBundleId: 'com.filipdoganowski.travelCostLog',
  );
}
